# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Default name', max_length=100)),
                ('app_id', models.CharField(max_length=400)),
                ('secret', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Default name', max_length=100)),
                ('description', models.CharField(default=b'Default description', max_length=400)),
                ('latch_status', models.BooleanField(default=True)),
                ('regex', models.CharField(default=b'', max_length=400)),
                ('method', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=400)),
                ('body', models.CharField(max_length=800)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hooks.Application')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hooks.Hook'),
        ),
    ]
