# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default=b'Default name', max_length=100),
        ),
    ]
