# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0002_auto_20160923_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='response',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
